USE [master]
GO

/****** Object:  Database [Hackathon]    Script Date: 09-03-23 12:26:01 ******/
CREATE DATABASE [Hackathon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hackathon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.TFTIC\MSSQL\DATA\Hackathon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hackathon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.TFTIC\MSSQL\DATA\Hackathon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hackathon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hackathon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hackathon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hackathon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hackathon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hackathon] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hackathon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hackathon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hackathon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hackathon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hackathon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hackathon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hackathon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hackathon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hackathon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hackathon] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Hackathon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hackathon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hackathon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hackathon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hackathon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hackathon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hackathon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hackathon] SET RECOVERY FULL 
GO

ALTER DATABASE [Hackathon] SET  MULTI_USER 
GO

ALTER DATABASE [Hackathon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hackathon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hackathon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hackathon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hackathon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hackathon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Hackathon] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Hackathon] SET  READ_WRITE 
GO

